from cnn_inference import SnakeInference



snaky = SnakeInference()

state_action = {'gameState': {'height': 11,
                'width': 11,
                'food': [[7, 1], [5, 6], [10, 6]],
                'hazards': [],
                'players': [{'health': 100,
                    'body': [[3, 8]],
                    'head': [3, 8],
                    'length': 1,
                    'id': 1,
                    'alive': True,
                    'ours': True},
                {'health': 100,
                    'body': [[10, 6]],
                    'head': [10, 6],
                    'length': 1,
                    'id': 2,
                    'alive': True,
                    'ours': False},
                {'health': 100,
                    'body': [[6, 5]],
                    'head': [6, 5],
                    'length': 1,
                    'id': 3,
                    'alive': True,
                    'ours': False}],
                'endState': False,
                'won': False,
                'lost': False,
                'tie': False},
                'action': 'left',
                'reward': 0.0,
                'nextState': {'height': 11,
                'width': 11,
                'food': [[7, 1], [5, 6], [10, 6]],
                'hazards': [],
                'players': [{'health': 99,
                    'body': [[2, 8], [3, 8]],
                    'head': [2, 8],
                    'length': 2,
                    'id': 1,
                    'alive': True,
                    'ours': True},
                {'health': 99,
                    'body': [[9, 6], [10, 6]],
                    'head': [9, 6],
                    'length': 2,
                    'id': 2,
                    'alive': True,
                    'ours': False},
                {'health': 99,
                    'body': [[5, 5], [6, 5]],
                    'head': [5, 5],
                    'length': 2,
                    'id': 3,
                    'alive': True,
                    'ours': False}],
                'endState': False,
                'won': False,
                'lost': False,
                'tie': False}}

snaky.value(state_action)